[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false

[rpc_endpoints]
flare = "https://flare-api.flare.network/ext/C/rpc"
coston2 = "https://coston2-api.flare.network/ext/C/rpc"
songbird = "https://songbird-api.flare.network/ext/C/rpc"

[etherscan]
flare = { key = "${FLARE_ETHERSCAN_API_KEY}" }
coston2 = { key = "${COSTON2_ETHERSCAN_API_KEY}" }



